#!/bin/sh
set $term urxvt
#exec pkill battery.sh && $HOME/scripts/battery.sh

exec dunst
exec $HOME/scripts/battery.sh
exec udiskie -t
exec allow_rgb10_configs=false compton --backend glx
exec nitrogen --restore
exec $term -name scratchpad
exec $term -name ncmpcpp -e ncmpcpp
exec polybar main

#Super key for i3 keybindings
set $mod Mod4

#1 pixel border for all windows
default_border pixel 1
default_floating_border normal 0

#no need to follow mouse 
focus_follows_mouse no

#hide unnecessary borders
hide_edge_borders both

for_window [class=mpv] floating enable
for_window [class=mpv] sticky enable
for_window [class=Lxappearance] floating enable
for_window [class=Nitrogen] floating enable
assign [class=Chromium] $ws1
assign [instance=winword.exe] $ws3
assign [instance=powerpnt.exe] $ws3
assign [instance=excel.exe] $ws3
assign [class=Evince] $ws3
assign [class=Pcmanfm] $ws2
assign [title=ncmpcpp] $ws10
for_window [title=scratchpad] move scratchpad

#Font for titles
font pango:Anonymous Pro 8

# Use Mouse+$mod to drag floating windows to their wanted position
floating_modifier $mod

# start a terminal
bindsym $mod+Return exec $term

# kill focused window
bindsym $mod+Shift+q kill

# change focus
bindsym $mod+j focus left
bindsym $mod+k focus down
bindsym $mod+l focus up
bindsym $mod+semicolon focus right

# alternatively, you can use the cursor keys:
bindsym $mod+Left focus left
bindsym $mod+Down focus down
bindsym $mod+Up focus up
bindsym $mod+Right focus right

# move focused window
bindsym $mod+Shift+j move left
bindsym $mod+Shift+k move down
bindsym $mod+Shift+l move up
bindsym $mod+Shift+semicolon move right

# alternatively, you can use the cursor keys:
bindsym $mod+Shift+Left move left
bindsym $mod+Shift+Down move down
bindsym $mod+Shift+Up move up
bindsym $mod+Shift+Right move right

# split in horizontal orientation
bindsym $mod+h split h

# split in vertical orientation
bindsym $mod+v split v

# enter fullscreen mode for the focused container
bindsym $mod+f fullscreen toggle

# change container layout (stacked, tabbed, toggle split)
bindsym $mod+s layout stacking
bindsym $mod+w layout tabbed
bindsym $mod+e layout toggle split

# toggle tiling / floating
bindsym $mod+Shift+space floating toggle

# change focus between tiling / floating windows
bindsym $mod+space focus mode_toggle

# focus the parent container
bindsym $mod+a focus parent

# focus the child container
#bindsym $mod+d focus child

#toggle opacity of active window
bindsym $mod+t exec transset-df -ta > /dev/null

#show scratchpad
bindsym $mod+z scratchpad show 

#Some workspaces
set $ws1 "1: web"
set $ws2 "2: files"
set $ws3 "3: office"
set $ws4 "4: term"
set $ws5 "5"
set $ws6 "6"
set $ws7 "7"
set $ws8 "8"
set $ws9 "9"
set $ws10 "10: music"

# switch to workspace
bindsym $mod+1 workspace $ws1
bindsym $mod+2 workspace $ws2
bindsym $mod+3 workspace $ws3
bindsym $mod+4 workspace $ws4
bindsym $mod+5 workspace $ws5
bindsym $mod+6 workspace $ws6
bindsym $mod+7 workspace $ws7
bindsym $mod+8 workspace $ws8
bindsym $mod+9 workspace $ws9
bindsym $mod+0 workspace $ws10

# move focused container to workspace
bindsym $mod+Shift+1 move container to workspace $ws1
bindsym $mod+Shift+2 move container to workspace $ws2
bindsym $mod+Shift+3 move container to workspace $ws3
bindsym $mod+Shift+4 move container to workspace $ws4
bindsym $mod+Shift+5 move container to workspace $ws5
bindsym $mod+Shift+6 move container to workspace $ws6
bindsym $mod+Shift+7 move container to workspace $ws7
bindsym $mod+Shift+8 move container to workspace $ws8
bindsym $mod+Shift+9 move container to workspace $ws9
bindsym $mod+Shift+0 move container to workspace $ws10

# reload the configuration file
bindsym $mod+Shift+c reload
# restart i3 inplace (preserves your layout/session, can be used to upgrade i3)
bindsym $mod+Shift+r restart
# exit i3 (logs you out of your X session)
bindsym $mod+Shift+e exec "i3-nagbar -t warning -m 'You pressed the exit shortcut. Do you really want to exit i3? This will end your X session.' -b 'Yes, exit i3' 'i3-msg exit'"

# resize window (you can also use the mouse for that)
mode "resize" {
        # These bindings trigger as soon as you enter the resize mode

        # Pressing left will shrink the window’s width.
        # Pressing right will grow the window’s width.
        # Pressing up will shrink the window’s height.
        # Pressing down will grow the window’s height.
        bindsym j resize shrink width 10 px or 10 ppt
        bindsym k resize grow height 10 px or 10 ppt
        bindsym l resize shrink height 10 px or 10 ppt
        bindsym semicolon resize grow width 10 px or 10 ppt

        # same bindings, but for the arrow keys
        bindsym Left resize shrink width 10 px or 10 ppt
        bindsym Down resize grow height 10 px or 10 ppt
        bindsym Up resize shrink height 10 px or 10 ppt
        bindsym Right resize grow width 10 px or 10 ppt

        # back to normal: Enter or Escape or $mod+r
        bindsym Return mode "default"
        bindsym Escape mode "default"
        bindsym $mod+r mode "default"
}

bindsym $mod+r mode "resize"

bindsym $mod+Ctrl+Left resize shrink width 10 px or 10 ppt
bindsym $mod+Ctrl+Down resize grow height 10 px or 10 ppt
bindsym $mod+Ctrl+Up resize shrink height 10 px or 10 ppt
bindsym $mod+Ctrl+Right resize grow width 10 px or 10 ppt

bindsym $mod+Ctrl+j resize shrink width 10 px or 10 ppt
bindsym $mod+Ctrl+k resize grow height 10 px or 10 ppt
bindsym $mod+Ctrl+l resize shrink height 10 px or 10 ppt
bindsym $mod+Ctrl+semicolon resize grow width 10 px or 10 ppt

#bar {
#        status_command i3status
#}

bindsym $mod+c exec chromium
bindsym $mod+x exec gmrun
bindsym $mod+d exec pcmanfm
bindsym Print exec gnome-screenshot -i
bindsym $mod+m exec $HOME/scripts/lock.sh

bindsym XF86TouchpadToggle exec $HOME/scripts/touchpad.sh

bindsym XF86AudioStop exec mpc -q stop
bindsym XF86AudioNext exec mpc -q next
bindsym XF86AudioPrev exec mpc -q prev
bindsym XF86AudioPlay exec mpc -q toggle

#bindsym XF86MonBrightnessUp exec $HOME/scripts/backlight.sh set + 14
#bindsym XF86MonBrightnessDown exec $HOME/scripts/backlight.sh set + -14
bindsym XF86AudioMute exec amixer sset Master toggle
bindsym XF86AudioLowerVolume exec amixer sset Master 5%-
bindsym XF86AudioRaiseVolume exec amixer sset Master 5%+
bindsym XF86Sleep exec $HOME/scripts/lock.sh && systemctl suspend
bindsym $mod+F1 exec $HOME/scripts/lock.sh && systemctl hibernate


set $color0	    #1d1f21
set $color8	    #969896

set $color1	    #cc342b
set $color9	    #cc342b

set $color2	    #198844
set $color10	    #198844

set $color3	    #fba922
set $color11	    #fba922

set $color4	    #3971ed
set $color12	    #3971ed

set $color5	    #a36ac7
set $color13	    #a36ac7

set $color6	    #3971ed
set $color14	    #3971ed

set $color7	    #c5c8c6
set $color15	    #ffffff

#class				 border		background 	text		indicator	child_border
 client.focused			 $color3 	$color3 	$color0 	$color2		$color3
 client.focused_inactive	 $color8 	$color8 	$color0 	$color10 	$color8
 client.unfocused 		 $color0 	$color0 	$color7 	$color0 	$color0
 client.urgent			 $color1	$color1		$color0		$color9		$color0
